set(SDL2_INCLUDE_DIRS "${CMAKE_CURRENT_BINARY_DIR}/sdl2/include")
set(SDL2_LIB_DIR "${CMAKE_CURRENT_BINARY_DIR}/sdl2/lib/x64/")
set(SDL2_LIBRARIES "${CMAKE_CURRENT_BINARY_DIR}/sdl2/lib/x64/SDL2.lib;${CMAKE_CURRENT_BINARY_DIR}/sdl2/lib/x64/SDL2main.lib")
set(SDL2_RUNTIME_LIBRARIES "${CMAKE_CURRENT_BINARY_DIR}/sdl2/lib/x64/SDL2.dll")