# Lint the project using cpplint
name: Lint

on:
  # Branch pushes that do not only modify other workflow files
  push:
    branches:
      - '**'
    paths:
      - "**"
      - "!.github/**"
      - ".github/workflows/Lint.yml"
  # Disabled for now. See https://github.com/FLAMEGPU/FLAMEGPU2/pull/644
  # pull_request:
  # Allow manual invocation.
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  cpplint:
    runs-on: ${{ matrix.cudacxx.os }}
    name: "cpplint (${{ matrix.cudacxx.cuda }}, ${{ matrix.cudacxx.os }})"
    strategy:
      fail-fast: false
      # Multiplicative build matrix
      # optional exclude: can be partial, include: must be specific
      matrix:
        cudacxx:
          - cuda: "12.5"
            os: ubuntu-24.04
    env:
      # Define constants
      BUILD_DIR: "build"
      BUILD_TESTS: "ON"
      # Port matrix options to environment, for more portability.
      CUDA: ${{ matrix.cudacxx.cuda }}
      OS: ${{ matrix.cudacxx.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install cpplint
      run: |
        python3 -m pip install cpplint
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Add custom problem matchers for annotations
      run: echo "::add-matcher::.github/problem-matchers.json"

    - name: Configure cmake
      run: >
        cmake . -B "${{ env.BUILD_DIR }}"
        -DFLAMEGPU_ALLOW_LINT_ONLY=ON

    - name: Lint
      working-directory: ${{ env.BUILD_DIR }}
      run: cmake --build . --target all_lint --verbose -j `nproc` 

